#%RAML 0.8
title: "LocalAPI Example RAML"
version: "v1"
baseUri: "https://example.com"
protocols: [HTTPS]
mediaType: "application/json"

resourceTypes:
  - collection:
      description: Collection of available <<resourcePathName>>.
      get?:
        responses:
          200:
            description: Success!
            body:
              application/json:
                example: "example"
                schema: "schema"
  - collection-item:
      description: Entity representing a <<resourcePathName|!singularize>>
      get?:
        description: |
          Get the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}
        responses:
          200:
            description: Success!
            body:
              application/json:
                example: "example"
                schema: "schema"
/users:
  type: collection
  displayName: Users
  post:
    description: Creates a user with a system-generated id.
    body:
      application/json:
        example: !include examples/user_post.json
        schema: !include schemas/user_post.json
    responses:
      202:
        body:
          application/json:
            example: ""
            schema: ""
  get:
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/users.json
            example: !include examples/users.json
  /{userId}:
    type: collection-item
    uriParameters:
      userId:
        displayName: User ID
        type: string
        required: true
    patch:
        description: Updates a user partially by his/her id.
        body:
          application/json:
            example: !include examples/user_patch.json
            schema: !include schemas/user_patch.json
        responses:
          200:
            body:
              application/json:
                schema: !include schemas/user.json
                example: !include examples/user.json
    put:
      body:
        application/json:
          schema: !include schemas/user_put.json
          example: !include examples/user.json
      responses:
        200:
          body:
            application/json:
              example: false
    delete:
      responses:
        200:
          body:
            application/json:
              example: ""
    get:
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/user.json
              example: !include examples/user.json