#%RAML 0.8
title: "AirAsia REST API"
version: "v2"
baseUri: "https://airasia.isaacloud.com/api/{version}"
protocols: [HTTPS]
mediaType: "application/json"
schemas: 
    - 
        "User": |
                {
                  "type": "object",
                  "title": "User",
                  "description": "Representation of user",
                  "required": false,
                  "additionalProperties": false,
                  "properties": {
                    "_id": {
                      "type": "string",
                      "description": "User id",
                      "required": true
                    },
                    "image": {
                      "type": "string",
                      "description": "User image",
                      "required": true
                    },
                    "badges": {
                      "type": "object",
                      "title": "Badges",
                      "description": "User badges catalog",
                      "required": true
                    },
                    "email": {
                      "type": "string",
                      "title": "E-Mail",
                      "description": "User email address",
                      "required": true
                    },
                    "firstName": {
                      "type": "string",
                      "title": "First Name",
                      "description": "User first name",
                      "required": true
                    },
                    "flights": {
                      "type": "object",
                      "title": "Flights",
                      "description": "Flights informations",
                      "required": true,
                      "properties": {
                        "distance": {
                          "type": "number",
                          "title": "Distance",
                          "description": "Distance in kilometeres",
                          "minimum": "0",
                          "required": true
                        },
                        "numberOf": {
                          "type": "number",
                          "title": "Number Of",
                          "description": "Number of flights",
                          "minimum": "0",
                          "required": true
                        }
                      }
                    },
                    "lastName": {
                      "type": "string",
                      "title": "Last Name",
                      "description": "User last name",
                      "required": true
                    },
                    "level": {
                      "type": "number",
                      "title": "Level",
                      "description": "User level",
                      "minimum": "0",
                      "required": true
                    },
                    "notifications": {
                      "type": "array",
                      "title": "Notifications",
                      "description": "Collection of user notifications",
                      "minitems": "0",
                      "required": true,
                      "items": {
                        "type": "object",
                        "title": "Notification",
                        "required": false,
                        "properties": {
                          "createAt": {
                            "type": "string",
                            "description": "Notification creation time",
                            "required": true
                          },
                          "description": {
                            "type": "object",
                            "title": "Notification description",
                            "additionalProperties": true
                          },
                          "image-50x50": {
                            "type": "string",
                            "description": "Small image",
                            "id": "http://jsonschema.net/notifications/0/images/50x50",
                            "required": true
                          },
                          "image-75x75": {
                            "type": "string",
                            "description": "Normal image",
                            "id": "http://jsonschema.net/notifications/0/images/75x75",
                            "required": true
                          },
                          "read": {
                            "type": "boolean",
                            "required": true
                          },
                          "facebook": {
                            "type": "object",
                            "title": "Facebook",
                            "description": " For more information see https://developers.facebook.com/docs/graph-api/reference/v2.1/user/feed",
                            "id": "http://jsonschema.net/notifications/0/share/facebook",
                            "required": true,
                            "properties": {
                              "description": {
                                "type": "object",
                                "description": "Description of share item",
                                "required": true,
                                "additionalProperties": true
                              },
                              "title": {
                                "type": "object",
                                "description": "Title of share item",
                                "required": true,
                                "additionalProperties": true
                              }
                            }
                          },
                          "twitter": {
                            "type": "object",
                            "title": "Twitter",
                            "description": " For more information see https://dev.twitter.com/rest/reference/post/statuses/update",
                            "required": false,
                            "properties": {
                              "status": {
                                "type": "object",
                                "description": "The text of your status update, typically up to 140 characters. URL encode as necessary. t.co link wrapping may affect character counts.",
                                "required": true,
                                "additionalProperties": true
                              }
                            }
                          },
                          "title": {
                            "type": "object",
                            "title": "Title of notification",
                            "description": "Title of notification",
                            "required": true,
                            "additionalProperties": true
                          },
                          "type": {
                            "type": "string",
                            "description": "Type of notification",
                            "required": true,
                            "enum": [
                              "badgeErn",
                              "lvlUp",
                              "lbUp"
                            ],
                            "default": "badgeErn"
                          }
                        }
                      }
                    },
                    "points": {
                      "type": "number",
                      "description": "User points",
                      "minimum": "0",
                      "required": true
                    },
                    "tags": {
                      "type": "array",
                      "title": "List of user tags",
                      "minitems": "0",
                      "maxitems": "100",
                      "required": true,
                      "items": {
                        "type": "string",
                        "id": "http://jsonschema.net/tags/0",
                        "required": false
                      }
                    },
                    "facebook": {
                            "type": "object",
                            "title": "Facebook",
                            "description": " For more information see https://developers.facebook.com/docs/graph-api/reference/v2.1/user/feed",
                            "required": true,
                            "properties": {
                              "description": {
                                "type": "object",
                                "description": "Description of share item",
                                "required": true,
                                "additionalProperties": true
                              },
                              "title": {
                                "type": "object",
                                "description": "Title of share item",
                                "required": true,
                                "additionalProperties": true
                              }
                            }
                          },
                          "twitter": {
                            "type": "object",
                            "title": "Twitter",
                            "description": " For more information see https://dev.twitter.com/rest/reference/post/statuses/update",
                            "required": false,
                            "properties": {
                              "status": {
                                "type": "object",
                                "description": "The text of your status update, typically up to 140 characters. URL encode as necessary. t.co link wrapping may affect character counts.",
                                "required": true,
                                "additionalProperties": true
                              }
                            }
                          },
                  }
                }
    - 
        "Users": |
                {
                  "title": "User",
                  "description": "Representation of user",
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string",
                      "format": "email",
                      "description": "User email address",
                      "required": true
                    },
                    "firstName": {
                      "type": "string",
                      "description": "User first name",
                      "minLength": 4,
                      "default": "John",
                      "required": true
                    },
                    "lastName": {
                      "type": "string",
                      "description": "User last name",
                      "minLength": 4,
                      "default": "Doe",
                      "required": true
                    },
                    "level": {
                      "type": "number",
                      "description": "User level",
                      "minimum": 0,
                      "default": "Doe",
                      "required": true
                    },
                    "tags": {
                      "title": "List of user tags",
                      "type": "array",
                      "uniqueItems": true,
                      "required": false,
                      "items": {
                        "minLength": 2,
                        "maxLength": 32,
                        "type": "string"
                      }
                    },
                    "avatar": {
                      "type": "string",
                      "format": "uri",
                      "description": "User avatar",
                      "default": "http://placehold.it/120x120"
                    },
                    "badges": {
                      "type": "object",
                      "description": "User badges catalog",
                      "required": true,
                      "title": "Badges",
                      "properties": {}
                    },
                    "flights": {
                      "type": "object",
                      "description": "Flights informations",
                      "required": true,
                      "title": "Flights",
                      "properties": {
                        "numberOf": {
                          "minimum": 0,
                          "type": "number",
                          "description": "Number of flights",
                          "required": true
                        },
                        "distance": {
                          "type": "number",
                          "minimum": 0,
                          "description": "Distance in kilometeres",
                          "required": true
                        }
                      }
                    },
                    "points": {
                      "type": "number",
                      "minimum": 0,
                      "description": "User points",
                      "required": true
                    },
                    "notifications": {
                      "type": "array",
                      "format": "table",
                      "title": "Notifications",
                      "uniqueItems": true,
                      "items": {
                        "type": "object",
                        "title": "Notification",
                        "properties": {
                          "type": {
                            "type": "string",
                            "enum": [
                              "badgeErn",
                              "lvlUp",
                              "lbUp"
                            ],
                            "description": "Type of notification",
                            "default": "badgeErn",
                            "required": true
                          },
                          "isRead": {
                            "type": "boolean",
                            "default": false,
                            "title": "isRead"
                          },
                          "pictures": {
                            "type": "object",
                            "title": "Pictures",
                            "properties": {
                              "50x50": {
                                "description": "Small image",
                                "type": "string",
                                "default": "http://placehold.it/50x50",
                                "required": true
                              },
                              "75x75": {
                                "description": "Normal image",
                                "type": "string",
                                "default": "http://placehold.it/75x75",
                                "required": true
                              }
                            }
                          },
                          "title": {
                            "type": "object",
                            "title": "Title of notification",
                            "required": true,
                            "uniqueItems": true,
                            "properties": {
                              "key": {
                                "type": "string",
                                "description": "Key of translation",
                                "required": true
                              },
                              "variables": {
                                "type": "object",
                                "title": "List of variables",
                                "required": false,
                                "uniqueItems": true,
                                "properties": {
                                  "*": {
                                    "type": "string"
                                  }
                                }
                              }
                            }
                          },
                          "description": {
                            "type": "object",
                            "title": "Notification description",
                            "required": true,
                            "uniqueItems": true,
                            "properties": {
                              "key": {
                                "type": "string",
                                "description": "Key of the translation",
                                "required": true
                              },
                              "variables": {
                                "type": "object",
                                "title": "List of variables",
                                "required": false,
                                "uniqueItems": true,
                                "properties": {
                                  "*": {
                                    "type": "string"
                                  }
                                }
                              }
                            }
                          },
                          "createAt": {
                            "format": "date-time",
                            "type": "string",
                            "description": "Notification creation time",
                            "required": true,
                            "default": "2012-04-23T18:25:43.511Z"
                          },
                          "social": {
                            "type": "object",
                            "description": "Social media integration integration",
                            "title": "Social",
                            "properties": {
                              "facebook": {
                                "required": true,
                                "type": "object",
                                "description": " For more information see https://developers.facebook.com/docs/graph-api/reference/v2.1/user/feed",
                                "title": "Facebook",
                                "properties": {
                                  "message": {
                                    "type": "string",
                                    "minLength": 4,
                                    "maxLength": 256,
                                    "required": true,
                                    "description": "The main body of the post, otherwise called the status message"
                                  },
                                  "link": {
                                    "required": true,
                                    "type": "object",
                                    "title": "Link",
                                    "description": "The URL of a link to attach to the post. Either link, place, or message must be supplied. Additional fields associated with link are shown below.",
                                    "properties": {
                                      "picture": {
                                        "type": "string",
                                        "default": "http://placehold.it/100x100",
                                        "description": "Overwrites the description in the link preview",
                                        "required": true
                                      },
                                      "name": {
                                        "type": "string",
                                        "default": "name",
                                        "description": "Overwrites the title of the link preview.",
                                        "required": true
                                      },
                                      "caption": {
                                        "type": "string",
                                        "default": "caption",
                                        "description": "Overwrites the caption under the title in the link preview.",
                                        "required": true
                                      },
                                      "description": {
                                        "type": "string",
                                        "default": "description",
                                        "description": "Overwrites the description in the link preview",
                                        "required": true
                                      }
                                    }
                                  }
                                }
                              },
                              "twitter": {
                                "type": "object",
                                "title": "Twitter",
                                "description": " For more information see https://dev.twitter.com/rest/reference/post/statuses/update",
                                "properties": {
                                  "status": {
                                    "type": "string",
                                    "minLength": 4,
                                    "maxLength": 140,
                                    "required": true,
                                    "description": "The text of your status update, typically up to 140 characters. URL encode as necessary. t.co link wrapping may affect character counts."
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
    - 
        "Badge": |
                {
                  "$schema": "http://json-schema.org/draft-04/schema",
                  "title": "Badge",
                  "description": "Representation of badge",
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string",
                      "description": "User id",
                      "required": true
                    },
                    "type": {
                      "type": "string",
                      "enum": [
                        "oneTime",
                        "progressive"
                      ],
                      "description": "Type of badge",
                      "default": "oneTime",
                      "required": true
                    },
                    "level": {
                      "description": "Level of badge",
                      "required": true,
                      "type": "number"
                    },
                    "name": {
                      "type": "object",
                      "title": "Badge name",
                      "uniqueItems": true,
                      "description": "Name of badge",
                      "required": true,
                      "additionalProperties": true
                    },
                    "description": {
                      "type": "object",
                      "title": "Badge description",
                      "required": true,
                      "uniqueItems": true,
                      "additionalProperties": true
                    },
                    "picture-50x50": {
                          "description": "Small size of badge picture",
                          "type": "string",
                          "default": "http://placehold.it/50x50",
                          "required": true
                    },
                    "picture-75x75": {
                          "description": "Normal size of badge picture",
                          "type": "string",
                          "default": "http://placehold.it/75x75",
                          "required": true
                    },
                    "category": {
                      "title": "Badge category",
                      "required": true,
                      "default": "categoryName",
                      "type": "string"
                    },
                    "tags": {
                      "title": "List of badge tags",
                      "type": "array",
                      "uniqueItems": true,
                      "required": false,
                      "items": {
                        "minLength": 2,
                        "maxLength": 32,
                        "type": "string"
                      }
                    },
                    "createAt": {
                      "format": "date-time",
                      "type": "string",
                      "description": "Badge creation time",
                      "required": true,
                      "default": "2012-04-23T18:25:43.511Z"
                    },
                    "points": {
                      "type": "number",
                      "description": "User points",
                      "minimum": "0",
                      "required": true
                    },
                    "facebook": {
                                "type": "object",
                                "title": "Facebook",
                                "description": " For more information see https://developers.facebook.com/docs/graph-api/reference/v2.1/user/feed",
                                "id": "http://jsonschema.net/notifications/0/share/facebook",
                                "required": true,
                                "properties": {
                                  "description": {
                                    "type": "object",
                                    "description": "Description of share item",
                                    "required": true,
                                    "additionalProperties": true
                                  },
                                  "title": {
                                    "type": "object",
                                    "description": "Title of share item",
                                    "required": true,
                                    "additionalProperties": true
                                  }
                                }
                              },
                              "twitter": {
                                "type": "object",
                                "title": "Twitter",
                                "description": " For more information see https://dev.twitter.com/rest/reference/post/statuses/update",
                                "required": false,
                                "properties": {
                                  "status": {
                                    "type": "object",
                                    "description": "The text of your status update, typically up to 140 characters. URL encode as necessary. t.co link wrapping may affect character counts.",
                                    "required": true,
                                    "additionalProperties": true
                                  }
                                }
                              }
                  }
                }
    - 
        "Badges": |
                {
                  "$schema": "http://json-schema.org/draft-04/schema",
                  "title": "Badge",
                  "description": "Representation of badge",
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string",
                      "description": "User id",
                      "required": true
                    },
                    "type": {
                      "type": "string",
                      "enum": [
                        "oneTime",
                        "progressive"
                      ],
                      "description": "Type of badge",
                      "default": "oneTime",
                      "required": true
                    },
                    "level": {
                      "description": "Level of badge",
                      "required": true,
                      "type": "number"
                    },
                    "name": {
                      "type": "object",
                      "title": "Badge name",
                      "uniqueItems": true,
                      "description": "Name of badge",
                      "required": true,
                      "additionalProperties": true
                    },
                    "description": {
                      "type": "object",
                      "title": "Badge description",
                      "required": true,
                      "uniqueItems": true,
                      "additionalProperties": true
                    },
                    "picture-50x50": {
                          "description": "Small size of badge picture",
                          "type": "string",
                          "default": "http://placehold.it/50x50",
                          "required": true
                    },
                    "picture-75x75": {
                          "description": "Normal size of badge picture",
                          "type": "string",
                          "default": "http://placehold.it/75x75",
                          "required": true
                    },
                    "category": {
                      "title": "Badge category",
                      "required": true,
                      "default": "categoryName",
                      "type": "string"
                    },
                    "tags": {
                      "title": "List of badge tags",
                      "type": "array",
                      "uniqueItems": true,
                      "required": false,
                      "items": {
                        "minLength": 2,
                        "maxLength": 32,
                        "type": "string"
                      }
                    },
                    "createAt": {
                      "format": "date-time",
                      "type": "string",
                      "description": "Badge creation time",
                      "required": true,
                      "default": "2012-04-23T18:25:43.511Z"
                    },
                    "points": {
                      "type": "number",
                      "description": "User points",
                      "minimum": "0",
                      "required": true
                    },
                    "facebook": {
                                "type": "object",
                                "title": "Facebook",
                                "description": " For more information see https://developers.facebook.com/docs/graph-api/reference/v2.1/user/feed",
                                "id": "http://jsonschema.net/notifications/0/share/facebook",
                                "required": true,
                                "properties": {
                                  "description": {
                                    "type": "object",
                                    "description": "Description of share item",
                                    "required": true,
                                    "additionalProperties": true
                                  },
                                  "title": {
                                    "type": "object",
                                    "description": "Title of share item",
                                    "required": true,
                                    "additionalProperties": true
                                  }
                                }
                              },
                              "twitter": {
                                "type": "object",
                                "title": "Twitter",
                                "description": " For more information see https://dev.twitter.com/rest/reference/post/statuses/update",
                                "required": false,
                                "properties": {
                                  "status": {
                                    "type": "object",
                                    "description": "The text of your status update, typically up to 140 characters. URL encode as necessary. t.co link wrapping may affect character counts.",
                                    "required": true,
                                    "additionalProperties": true
                                  }
                                }
                              }
                  }
                }
    - 
        "Error": |
                {
                    "$schema": "http://json-schema.org/draft-03/schema",
                    "title": "Error definition",
                    "description": "Representation of error",
                    "properties": {
                        "code": {
                            "required": true,
                            "type": "number",
                            "description": "The internal code of the error"
                        },
                        "message": {
                            "required": true,
                            "type": "string",
                            "description": "Simple message or hashcode exaplaining the error"
                        },
                        "data": {
                            "required": false,
                            "type": "object",
                            "description": "Additional information for some of the errors",
                            "uniqueItems": true,
                            "properties": {
                            "*": {
                              "type": "string"
                            }
                          }
                        }
                    }
                }
resourceTypes: 
    - 
        "collection": 
            displayName: "collection"
    - 
        "collection-item": 
            displayName: "collection-item"
traits: 
    - 
        "pageable": 
            displayName: "pageable"
    - 
        "tagable": 
            displayName: "tagable"
    - 
        "orderable": 
            displayName: "orderable"
    - 
        "query": 
            displayName: "query"
securitySchemes: 
    - 
        "oauth_2_0": 
            description: |
                We use OAuth2 server implementation for authentication. It is an open standard and it provides a method for clients to access server resources on behalf of a resource owner.
            type: "OAuth 2.0"
            describedBy: 
                headers: 
                    "Authorization": 
                        description: |
                            Used to send a valid OAuth 2 access token. Do not use
                            with the "access_token" query string parameter.
                        type: string
                        required: false
                        repeat: false
                responses: 
                    "401": 
                        description: |
                            Bad or expired token. This can happen if the user or Dropbox
                            revoked or expired an access token. To fix, you should re-
                            authenticate the user.
                    "403": 
                        description: |
                            Bad OAuth request (wrong consumer key, bad nonce, expired
                            timestamp...). Unfortunately, re-authenticating the user won't help here.  
            settings: 
                "accessTokenUri": "https://airasia.isaacloud/token"
                "authorizationUri": "https://airasia.isaacloud/authorize"
                "baseUri": "https://airasia.isaacloud"
securedBy: 
    - 
        oauth_2_0
"/users": 
    displayName: "Users"
    description: "Collection of available users."
    type: "collection"
    get: 
        description: "Use this method to get the list of users."
        queryParameters: 
            "offset": 
                description: "Skip over a number of elements by specifying an offset value for the query"
                type: integer
                required: false
                repeat: false
                default: "0"
                example: "20"
            "limit": 
                description: "Limit the number of elements on the response"
                type: integer
                required: false
                repeat: false
                default: "10"
                example: "80"
            "groups": 
                description: "the tags we want to narrow down our search to"
                type: string
                required: false
                repeat: false
                example: "foo,bar"
            "orderBy": 
                description: "the fields we want to order by and the type of ordering"
                type: string
                required: false
                repeat: false
                example: "id:DESC,foo:ASC"
        responses: 
            "200": 
                description: "Success!"
                body: 
                    "application/json": 
                        schema: "Users"
                        example: |
                            {
                              "_id": "544f6d0ced5b2fca65a9f55b",
                              "index": 0,
                              "isActive": "Tue Sep 06 2005 19:56:50 GMT+0200 (CEST)",
                              "points": 3183,
                              "level": 4,
                              "avatar": "http://placehold.it/32x32",
                              "eyeColor": "brown",
                              "name": "Gates Marsh",
                              "gender": "male",
                              "company": "COMTOURS",
                              "email": "gatesmarsh@comtours.com",
                              "phone": "+1 (959) 484-2986",
                              "address": "128 Bayard Street, Garberville, Wyoming, 3389",
                              "tags": [
                                "et",
                                "elit",
                                "ut",
                                "laboris"
                              ],
                              "badges": {
                                "toErn": [
                                  {
                                    "id": "544f6d0c461e8d4fbf68dd5e",
                                    "name": "esse proident",
                                    "tags": [
                                      "aliqua",
                                      "proident"
                                    ],
                                    "description": "aliquip Lorem est nulla in nostrud quis est dolor sit"
                                  },
                                  {
                                    "id": "544f6d0c1dc2d59cec551a17",
                                    "name": "aute sunt",
                                    "tags": [
                                      "quis",
                                      "mollit"
                                    ],
                                    "description": "ea ex veniam mollit adipisicing magna officia Lorem aliqua id"
                                  },
                                  {
                                    "id": "544f6d0c584e66791602ef60",
                                    "name": "culpa consectetur",
                                    "tags": [
                                      "excepteur",
                                      "dolore"
                                    ],
                                    "description": "non culpa laboris nostrud consectetur velit Lorem qui magna laboris"
                                  }
                                ],
                                "erned": [
                                  {
                                    "id": "544f6d0c9b2c1f6c2451f50d",
                                    "name": "esse consectetur",
                                    "tags": [
                                      "veniam",
                                      "amet"
                                    ],
                                    "description": "anim commodo nostrud nisi tempor duis dolore amet deserunt in"
                                  },
                                  {
                                    "id": "544f6d0c5392fa4bfcb2094b",
                                    "name": "ipsum qui",
                                    "tags": [
                                      "laboris",
                                      "ullamco"
                                    ],
                                    "description": "ullamco ut irure minim elit elit ea Lorem mollit laborum"
                                  },
                                  {
                                    "id": "544f6d0ca1b37d6241c45916",
                                    "name": "nostrud culpa",
                                    "tags": [
                                      "officia",
                                      "dolore"
                                    ],
                                    "description": "commodo aliqua nostrud sint veniam deserunt proident anim minim velit"
                                  },
                                  {
                                    "id": "544f6d0c56a3fef6395fed1f",
                                    "name": "excepteur deserunt",
                                    "tags": [
                                      "commodo",
                                      "proident"
                                    ],
                                    "description": "eiusmod occaecat consequat nulla laboris veniam nostrud exercitation culpa minim"
                                  }
                                ]
                              },
                              "notifications": [
                                {
                                  "id": 0,
                                  "read": false,
                                  "type": "badge",
                                  "key": "pariatur excepteur tempor in cillum et eu veniam nulla est",
                                  "variables": {
                                    "key": "value"
                                  }
                                },
                                {
                                  "id": 1,
                                  "read": false,
                                  "type": "badge",
                                  "key": "esse adipisicing anim cillum consequat pariatur exercitation ad culpa laborum",
                                  "variables": {
                                    "key": "value"
                                  }
                                },
                                {
                                  "id": 2,
                                  "read": false,
                                  "type": "badge",
                                  "key": "incididunt duis cillum adipisicing excepteur non anim laborum tempor occaecat",
                                  "variables": {
                                    "key": "value"
                                  }
                                }
                              ],
                              "friends": [
                                {
                                  "id": "544f6d0cbf947426b9d8fccc",
                                  "name": "Twila Joyner"
                                },
                                {
                                  "id": "544f6d0c34b772c79d8970af",
                                  "name": "Murray Nolan"
                                },
                                {
                                  "id": "544f6d0cbb83af4715a7251d",
                                  "name": "Laura Ayala"
                                }
                              ],
                              "greeting": "Hello, Gates Marsh! You have 7 unread messages.",
                              "favoriteFruit": "apple"
                            }
            "404": 
                description: "user not found"
                body: 
                    "application/json": 
                        schema: "Error"
                        example: ""
        is: ["pageable", "tagable", "orderable"]
        securedBy: 
            - 
                oauth_2_0
    "/{userId}": 
        displayName: "User"
        description: "Entity representing a user"
        uriParameters: 
            "userId": 
                displayName: "userId"
                description: "UTest test."
                type: string
                required: true
                repeat: false
        type: "collection-item"
        get: 
            description: "Get the user with `id = {userId}`."
            responses: 
                "200": 
                    description: "Success!"
                    body: 
                        "application/json": 
                            schema: "User"
                            example: |
                                {
                                  "_id": "544f6d0ced5b2fca65a9f55b",
                                  "index": 0,
                                  "isActive": "Tue Sep 06 2005 19:56:50 GMT+0200 (CEST)",
                                  "points": 3183,
                                  "level": 4,
                                  "avatar": "http://placehold.it/32x32",
                                  "eyeColor": "brown",
                                  "name": "Gates Marsh",
                                  "gender": "male",
                                  "company": "COMTOURS",
                                  "email": "gatesmarsh@comtours.com",
                                  "phone": "+1 (959) 484-2986",
                                  "address": "128 Bayard Street, Garberville, Wyoming, 3389",
                                  "tags": [
                                    "et",
                                    "elit",
                                    "ut",
                                    "laboris"
                                  ],
                                  "badges": {
                                    "toErn": [
                                      {
                                        "id": "544f6d0c461e8d4fbf68dd5e",
                                        "name": "esse proident",
                                        "tags": [
                                          "aliqua",
                                          "proident"
                                        ],
                                        "description": "aliquip Lorem est nulla in nostrud quis est dolor sit"
                                      },
                                      {
                                        "id": "544f6d0c1dc2d59cec551a17",
                                        "name": "aute sunt",
                                        "tags": [
                                          "quis",
                                          "mollit"
                                        ],
                                        "description": "ea ex veniam mollit adipisicing magna officia Lorem aliqua id"
                                      },
                                      {
                                        "id": "544f6d0c584e66791602ef60",
                                        "name": "culpa consectetur",
                                        "tags": [
                                          "excepteur",
                                          "dolore"
                                        ],
                                        "description": "non culpa laboris nostrud consectetur velit Lorem qui magna laboris"
                                      }
                                    ],
                                    "erned": [
                                      {
                                        "id": "544f6d0c9b2c1f6c2451f50d",
                                        "name": "esse consectetur",
                                        "tags": [
                                          "veniam",
                                          "amet"
                                        ],
                                        "description": "anim commodo nostrud nisi tempor duis dolore amet deserunt in"
                                      },
                                      {
                                        "id": "544f6d0c5392fa4bfcb2094b",
                                        "name": "ipsum qui",
                                        "tags": [
                                          "laboris",
                                          "ullamco"
                                        ],
                                        "description": "ullamco ut irure minim elit elit ea Lorem mollit laborum"
                                      },
                                      {
                                        "id": "544f6d0ca1b37d6241c45916",
                                        "name": "nostrud culpa",
                                        "tags": [
                                          "officia",
                                          "dolore"
                                        ],
                                        "description": "commodo aliqua nostrud sint veniam deserunt proident anim minim velit"
                                      },
                                      {
                                        "id": "544f6d0c56a3fef6395fed1f",
                                        "name": "excepteur deserunt",
                                        "tags": [
                                          "commodo",
                                          "proident"
                                        ],
                                        "description": "eiusmod occaecat consequat nulla laboris veniam nostrud exercitation culpa minim"
                                      }
                                    ]
                                  },
                                  "notifications": [
                                    {
                                      "id": 0,
                                      "read": false,
                                      "type": "badge",
                                      "key": "pariatur excepteur tempor in cillum et eu veniam nulla est",
                                      "variables": {
                                        "key": "value"
                                      }
                                    },
                                    {
                                      "id": 1,
                                      "read": false,
                                      "type": "badge",
                                      "key": "esse adipisicing anim cillum consequat pariatur exercitation ad culpa laborum",
                                      "variables": {
                                        "key": "value"
                                      }
                                    },
                                    {
                                      "id": 2,
                                      "read": false,
                                      "type": "badge",
                                      "key": "incididunt duis cillum adipisicing excepteur non anim laborum tempor occaecat",
                                      "variables": {
                                        "key": "value"
                                      }
                                    }
                                  ],
                                  "friends": [
                                    {
                                      "id": "544f6d0cbf947426b9d8fccc",
                                      "name": "Twila Joyner"
                                    },
                                    {
                                      "id": "544f6d0c34b772c79d8970af",
                                      "name": "Murray Nolan"
                                    },
                                    {
                                      "id": "544f6d0cbb83af4715a7251d",
                                      "name": "Laura Ayala"
                                    }
                                  ],
                                  "greeting": "Hello, Gates Marsh! You have 7 unread messages.",
                                  "favoriteFruit": "apple"
                                }
                "404": 
                    description: "user not found"
                    body: 
                        "application/json": 
                            schema: |
                                {
                                    "$schema": "http://json-schema.org/draft-03/schema",
                                    "title": "Error definition",
                                    "description": "Representation of error",
                                    "properties": {
                                        "code": {
                                            "required": true,
                                            "type": "number",
                                            "description": "The internal code of the error"
                                        },
                                        "message": {
                                            "required": true,
                                            "type": "string",
                                            "description": "Simple message or hashcode exaplaining the error"
                                        },
                                        "data": {
                                            "required": false,
                                            "type": "object",
                                            "description": "Additional information for some of the errors",
                                            "uniqueItems": true,
                                            "properties": {
                                            "*": {
                                              "type": "string"
                                            }
                                          }
                                        }
                                    }
                                }
                            example: ""
            securedBy: 
                - 
                    oauth_2_0
"/badges": 
    displayName: "Badges"
    description: "Collection of available badges."
    type: "collection"
    get: 
        description: "Use this method to get the list of badges."
        queryParameters: 
            "offset": 
                description: "Skip over a number of elements by specifying an offset value for the query"
                type: integer
                required: false
                repeat: false
                default: "0"
                example: "20"
            "limit": 
                description: "Limit the number of elements on the response"
                type: integer
                required: false
                repeat: false
                default: "10"
                example: "80"
            "groups": 
                description: "the tags we want to narrow down our search to"
                type: string
                required: false
                repeat: false
                example: "foo,bar"
            "orderBy": 
                description: "the fields we want to order by and the type of ordering"
                type: string
                required: false
                repeat: false
                example: "id:DESC,foo:ASC"
        responses: 
            "200": 
                description: "Success!"
                body: 
                    "application/json": 
                        schema: "schema"
                        example: |
                            {
                              "_id": "544f6d0ced5b2fca65a9f55b",
                              "index": 0,
                              "isActive": "Tue Sep 06 2005 19:56:50 GMT+0200 (CEST)",
                              "points": 3183,
                              "level": 4,
                              "avatar": "http://placehold.it/32x32",
                              "eyeColor": "brown",
                              "name": "Gates Marsh",
                              "gender": "male",
                              "company": "COMTOURS",
                              "email": "gatesmarsh@comtours.com",
                              "phone": "+1 (959) 484-2986",
                              "address": "128 Bayard Street, Garberville, Wyoming, 3389",
                              "tags": [
                                "et",
                                "elit",
                                "ut",
                                "laboris"
                              ],
                              "badges": {
                                "toErn": [
                                  {
                                    "id": "544f6d0c461e8d4fbf68dd5e",
                                    "name": "esse proident",
                                    "tags": [
                                      "aliqua",
                                      "proident"
                                    ],
                                    "description": "aliquip Lorem est nulla in nostrud quis est dolor sit"
                                  },
                                  {
                                    "id": "544f6d0c1dc2d59cec551a17",
                                    "name": "aute sunt",
                                    "tags": [
                                      "quis",
                                      "mollit"
                                    ],
                                    "description": "ea ex veniam mollit adipisicing magna officia Lorem aliqua id"
                                  },
                                  {
                                    "id": "544f6d0c584e66791602ef60",
                                    "name": "culpa consectetur",
                                    "tags": [
                                      "excepteur",
                                      "dolore"
                                    ],
                                    "description": "non culpa laboris nostrud consectetur velit Lorem qui magna laboris"
                                  }
                                ],
                                "erned": [
                                  {
                                    "id": "544f6d0c9b2c1f6c2451f50d",
                                    "name": "esse consectetur",
                                    "tags": [
                                      "veniam",
                                      "amet"
                                    ],
                                    "description": "anim commodo nostrud nisi tempor duis dolore amet deserunt in"
                                  },
                                  {
                                    "id": "544f6d0c5392fa4bfcb2094b",
                                    "name": "ipsum qui",
                                    "tags": [
                                      "laboris",
                                      "ullamco"
                                    ],
                                    "description": "ullamco ut irure minim elit elit ea Lorem mollit laborum"
                                  },
                                  {
                                    "id": "544f6d0ca1b37d6241c45916",
                                    "name": "nostrud culpa",
                                    "tags": [
                                      "officia",
                                      "dolore"
                                    ],
                                    "description": "commodo aliqua nostrud sint veniam deserunt proident anim minim velit"
                                  },
                                  {
                                    "id": "544f6d0c56a3fef6395fed1f",
                                    "name": "excepteur deserunt",
                                    "tags": [
                                      "commodo",
                                      "proident"
                                    ],
                                    "description": "eiusmod occaecat consequat nulla laboris veniam nostrud exercitation culpa minim"
                                  }
                                ]
                              },
                              "notifications": [
                                {
                                  "id": 0,
                                  "read": false,
                                  "type": "badge",
                                  "key": "pariatur excepteur tempor in cillum et eu veniam nulla est",
                                  "variables": {
                                    "key": "value"
                                  }
                                },
                                {
                                  "id": 1,
                                  "read": false,
                                  "type": "badge",
                                  "key": "esse adipisicing anim cillum consequat pariatur exercitation ad culpa laborum",
                                  "variables": {
                                    "key": "value"
                                  }
                                },
                                {
                                  "id": 2,
                                  "read": false,
                                  "type": "badge",
                                  "key": "incididunt duis cillum adipisicing excepteur non anim laborum tempor occaecat",
                                  "variables": {
                                    "key": "value"
                                  }
                                }
                              ],
                              "friends": [
                                {
                                  "id": "544f6d0cbf947426b9d8fccc",
                                  "name": "Twila Joyner"
                                },
                                {
                                  "id": "544f6d0c34b772c79d8970af",
                                  "name": "Murray Nolan"
                                },
                                {
                                  "id": "544f6d0cbb83af4715a7251d",
                                  "name": "Laura Ayala"
                                }
                              ],
                              "greeting": "Hello, Gates Marsh! You have 7 unread messages.",
                              "favoriteFruit": "apple"
                            }
            "404": 
                description: "badge not found"
                body: 
                    "application/json": 
                        schema: "Error"
                        example: ""
        is: ["pageable", "tagable", "orderable"]
        securedBy: 
            - 
                oauth_2_0
    "/{badgeId}": 
        displayName: "Badge"
        description: "Entity representing a badge"
        uriParameters: 
            "badgeId": 
                displayName: "badgeId"
                type: string
                required: true
                repeat: false
        type: "collection-item"
        get: 
            description: "Use this method to get a badge by its id."
            responses: 
                "200": 
                    description: "Success!"
                    body: 
                        "application/json": 
                            schema: "Badge"
                            example: |
                                {
                                  "_id": "544f6d0ced5b2fca65a9f55b",
                                  "index": 0,
                                  "isActive": "Tue Sep 06 2005 19:56:50 GMT+0200 (CEST)",
                                  "points": 3183,
                                  "level": 4,
                                  "avatar": "http://placehold.it/32x32",
                                  "eyeColor": "brown",
                                  "name": "Gates Marsh",
                                  "gender": "male",
                                  "company": "COMTOURS",
                                  "email": "gatesmarsh@comtours.com",
                                  "phone": "+1 (959) 484-2986",
                                  "address": "128 Bayard Street, Garberville, Wyoming, 3389",
                                  "tags": [
                                    "et",
                                    "elit",
                                    "ut",
                                    "laboris"
                                  ],
                                  "badges": {
                                    "toErn": [
                                      {
                                        "id": "544f6d0c461e8d4fbf68dd5e",
                                        "name": "esse proident",
                                        "tags": [
                                          "aliqua",
                                          "proident"
                                        ],
                                        "description": "aliquip Lorem est nulla in nostrud quis est dolor sit"
                                      },
                                      {
                                        "id": "544f6d0c1dc2d59cec551a17",
                                        "name": "aute sunt",
                                        "tags": [
                                          "quis",
                                          "mollit"
                                        ],
                                        "description": "ea ex veniam mollit adipisicing magna officia Lorem aliqua id"
                                      },
                                      {
                                        "id": "544f6d0c584e66791602ef60",
                                        "name": "culpa consectetur",
                                        "tags": [
                                          "excepteur",
                                          "dolore"
                                        ],
                                        "description": "non culpa laboris nostrud consectetur velit Lorem qui magna laboris"
                                      }
                                    ],
                                    "erned": [
                                      {
                                        "id": "544f6d0c9b2c1f6c2451f50d",
                                        "name": "esse consectetur",
                                        "tags": [
                                          "veniam",
                                          "amet"
                                        ],
                                        "description": "anim commodo nostrud nisi tempor duis dolore amet deserunt in"
                                      },
                                      {
                                        "id": "544f6d0c5392fa4bfcb2094b",
                                        "name": "ipsum qui",
                                        "tags": [
                                          "laboris",
                                          "ullamco"
                                        ],
                                        "description": "ullamco ut irure minim elit elit ea Lorem mollit laborum"
                                      },
                                      {
                                        "id": "544f6d0ca1b37d6241c45916",
                                        "name": "nostrud culpa",
                                        "tags": [
                                          "officia",
                                          "dolore"
                                        ],
                                        "description": "commodo aliqua nostrud sint veniam deserunt proident anim minim velit"
                                      },
                                      {
                                        "id": "544f6d0c56a3fef6395fed1f",
                                        "name": "excepteur deserunt",
                                        "tags": [
                                          "commodo",
                                          "proident"
                                        ],
                                        "description": "eiusmod occaecat consequat nulla laboris veniam nostrud exercitation culpa minim"
                                      }
                                    ]
                                  },
                                  "notifications": [
                                    {
                                      "id": 0,
                                      "read": false,
                                      "type": "badge",
                                      "key": "pariatur excepteur tempor in cillum et eu veniam nulla est",
                                      "variables": {
                                        "key": "value"
                                      }
                                    },
                                    {
                                      "id": 1,
                                      "read": false,
                                      "type": "badge",
                                      "key": "esse adipisicing anim cillum consequat pariatur exercitation ad culpa laborum",
                                      "variables": {
                                        "key": "value"
                                      }
                                    },
                                    {
                                      "id": 2,
                                      "read": false,
                                      "type": "badge",
                                      "key": "incididunt duis cillum adipisicing excepteur non anim laborum tempor occaecat",
                                      "variables": {
                                        "key": "value"
                                      }
                                    }
                                  ],
                                  "friends": [
                                    {
                                      "id": "544f6d0cbf947426b9d8fccc",
                                      "name": "Twila Joyner"
                                    },
                                    {
                                      "id": "544f6d0c34b772c79d8970af",
                                      "name": "Murray Nolan"
                                    },
                                    {
                                      "id": "544f6d0cbb83af4715a7251d",
                                      "name": "Laura Ayala"
                                    }
                                  ],
                                  "greeting": "Hello, Gates Marsh! You have 7 unread messages.",
                                  "favoriteFruit": "apple"
                                }
                "404": 
                    description: "badge not found"
                    body: 
                        "application/json": 
                            schema: |
                                {
                                    "$schema": "http://json-schema.org/draft-03/schema",
                                    "title": "Error definition",
                                    "description": "Representation of error",
                                    "properties": {
                                        "code": {
                                            "required": true,
                                            "type": "number",
                                            "description": "The internal code of the error"
                                        },
                                        "message": {
                                            "required": true,
                                            "type": "string",
                                            "description": "Simple message or hashcode exaplaining the error"
                                        },
                                        "data": {
                                            "required": false,
                                            "type": "object",
                                            "description": "Additional information for some of the errors",
                                            "uniqueItems": true,
                                            "properties": {
                                            "*": {
                                              "type": "string"
                                            }
                                          }
                                        }
                                    }
                                }
                            example: ""
            securedBy: 
                - 
                    oauth_2_0
documentation: 
    - 
        title: "Getting Started"
        content: ""
    - 
        title: "Basics of Authentication"
        content: ""
